### PR TITLE
Model building work [ParkingArea]

### PR DESCRIPTION
**Pull request by qoopen0815**
The working list for this PR
- [ ] Polygon reduction
- [x] Separate driveways and sidewalks
- [ ] Planting of trees
- [ ] Transcription of road signs

### CODE REVIEW

**Comment by RyodoTanaka** [comment]
I checked, and have some question.
## 1. Texture missing
The picture I take on this PR branch, looks that the texture for CityHall plant is missing.
I guess this is from apply missing of the material that you told me on the Discord.
But any way, I report this issue. 
Screenshot from 2020-08-05 11-16-42

## 2. No trees
I opened `Environment/vtc_environment_assy.blend`, and there are no trees.
But you listed the "Planting of trees".
Thus, I would like to ask you about this.
Screenshot from 2020-08-05 11-20-51

## 3. No transcripts
This issue is same as 2. issue.
There are neither no transcripts for road signs.
I also would like to ask you about this.

Best,

**Comment by qoopen0815** [comment]
Thank you for replying.

> 1. Texture missing

I am aware of the CityHall texture loss issue. 
This is not the main purpose of PR and I will tackle it another time.

> 2. No trees

We were going to plant the trees in Unity.
However, we expect this Blender data to be used in other applications (e.g. Choreonoid).
So I think we need to plant trees in the Blender world as well.

> 3. No transcripts

Sorry, I'm trying..

The process is complete when all the checklists at the top of the page have been completed.
Please check again at that time.

**Comment by RyodoTanaka** [comment]
@calm0815 
Thank you for your reply.
I miss understood about your list on the first comment.
I thought that is the feature that you want to marge with this PR.
I understand your will.

Thus, please not to write the ToDo lists on here, but to write the check list that you want to marge as new feature with this PR.
About the ToDo list, please create new Issue and write on there.

Bests,

**Comment by RyodoTanaka** [comment]
@calm0815 
So, what is the feature that you want to merge with this PR ?

**Comment by qoopen0815** [comment]
> Thus, please not to write the ToDo lists on here, but to write the check list that you want to marge as new feature with this PR.
About the ToDo list, please create new Issue and write on there.

OK.
I will do so since the next time.

> So, what is the feature that you want to merge with this PR ?

The features of this PR are the same as the checklist.

**Comment by RyodoTanaka** [comment]
@calm0815 
> The features of this PR are the same as the checklist.

If it is true, you need to add Trees & Transcripts & Reduce polygons.
But isn't it ToDo lists (wish lists) ?
If you want to add those feature with THIS PR, it still not implemented.
Thus, I could not merge it.
I think the list is too much with THIS PR.
And it is worth to merge with current states.

Best,

**Comment by qoopen0815** [comment]
I understood Issue and PR operations.
Next time, I'd like to present a wish list in Issue and achievements in PR.

For this PR, I will present the following results.

- [x] Reconfigure the directory.
- [x] Added texture tools.
- [x] Delete unnecessary files.

The initial wish list I was presenting goes to Issue.
Please check the Issue.

**Comment by RyodoTanaka** [comment]
@calm0815 
Thank you for your understanding.
The new featere list, I checked is working.
Thus I will merge it.

**Comment by qoopen0815** [comment]
Thank you for merging !
Please check again when ParkingArea is complete!

**Pull request merged**
